excerpt_separator: ""
pygments: true
#markdown: kramdown
url: http://zebular13.github.io
permalink: /blog/:year/:month/:day/:title
title: Zebular13
paginate: 10
paginate_path: "/blog/page:num/"
gems:
  - jekyll-sitemap
  - jekyll-paginate
auto: false  
server: false  
lsi: false  
markdown: rdiscount  
highlighter: true  
category_dir: topics  
category_title_prefix:  
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp"]  
destination: public  
